services:
  db:
    image: postgres:13.8
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/x-disk
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
